### ISSUE TITLE
[Front] Admin page

### ISSUE THREAD

**Issue by MatthewDlr** [smansteel/A2-genie-logiciel#11]
- [x] Create new module
- [x] Create a wallet within a module
- [ ] Edit competencies and sub-competencies of a wallet
- [x] Manage teachers permissions

**Comment by ghislaindemael** [comment]
Front for task 1 is done : Needing the link to DB

**Comment by ghislaindemael** [comment]
Added the possibility to select a module manager.

- [ ] Make the link to DB to save module state
- [ ] Restrict edition for appropriate roles
